### ISSUE TITLE
Street names in small villages

### ISSUE THREAD

**Issue by ChrisEt** [JOSM/austriaaddresshelper#11]
For some smaller villages, the reverse geocoder returns street names in the format `village/streetname`. This format is not only unknown to the [specification](https://wiki.openstreetmap.org/wiki/DE:Key:addr), it is also flagged as an error by [Osmose](http://osmose.openstreetmap.fr/de/map/#zoom=16&lat=46.81294&lon=14.36798&item=xxxx&level=1&tags=&fixable=).

**Example:**
9311 Kraig, N 46.81° E 14.37°

Is there any reference in OpenStreetMap that this format is allowed?

If not, that means that _austriaaddresshelper_ can produce illegal attribute values in some cases. Users might not be aware of this or simply trust the plugin to work standard-compliant, resulting in many erroneous entries into the OSM database.

In that case I suggest we implement some special treatment of values from the reverse geocoder to make values correct.

**Comment by thomaskonrad** [comment]
It's true that BEV Reverse Geocoder returns wrong street names in that area, and I'll fix that (there are lots of [corrections](https://github.com/thomaskonrad/bev-reverse-geocoder/blob/master/scripts/correct-data.sql) I have to do after an import).

By the way, the Osmose examples you mentioned are manually tagged street names. Austria Address Helper cannot tag street names only, it would also add other address tags and a source. But it looks like someone got "inspired" by the weird street names.

**Comment by thomaskonrad** [comment]
See https://github.com/thomaskonrad/bev-reverse-geocoder/issues/2. I'll close this issue as it's related with BEV Reverse Geocoder, not the JOSM plugin.

**Comment by ChrisEt** [comment]
I wasn't aware the BEV Reverse Geocoder is a separate GitHub project, but thanks a lot for fixing this so quickly!

You are right with your remark that the Osmose errors are on streets while the plugin generates tags on buildings, and that somebody tried to make these equal... :smiley:

**Comment by thomaskonrad** [comment]
The BEV Reverse Geocoder now returns correct street names ([example](https://bev-reverse-geocoder.thomaskonrad.at/reverse-geocode/json?lat=46.814002&lon=14.363844&distance=50&limit=3&epsg=4326)).

Thanks for reporting this!
