### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by markusstraub** [JOSM/austriaaddresshelper#15]
Currently the plugin does not work:

> An unexpected Exception occurred: javx.net.SSLException: Received fatal alert: internal_error

I figure this happens because the used geocoder (https://bev-reverse-geocoder.thomaskonrad.at/reverse-geocode/json) does not issue an SSL certificate - as can been seen when visiting this page with a browser. @thomaskonrad could you have a look at your domain's certificate? That would be great :)

**Comment by thomaskonrad** [comment]
I don't run the service any more. Please refer to the fork https://github.com/pkolmann/bev-reverse-geocoder which is, I think, actively developed.

**Comment by thomaskonrad** [comment]
Shall we change the default URL [here](https://github.com/JOSM/austriaaddresshelper/blob/5b2803216c96f6805ed41f7ea5300c5ec0f3834e/src/org/openstreetmap/josm/plugins/austriaaddresshelper/AustriaAddressHelperAction.java#L53) @don-vip? I'm not running the service any more, but [Philipp Kolmann is](https://github.com/pkolmann/bev-reverse-geocoder).

**Comment by pkolmann** [comment]
I've done a pull request long time ago:

https://github.com/JOSM/austriaaddresshelper/pull/14

**Comment by markusstraub** [comment]
Thanks for the quick reactions, I noticed you already described how to change the URL in JOSM to the new one here: https://github.com/JOSM/austriaaddresshelper/issues/12#issuecomment-673626134

Maybe that's helpful until @don-vip manages to merge the pull request.
